<h2><font color="brown">PANDAS 🐼 | Manipular e analisar dados em tabela </h2>

------


###  **PANDAS | O que é**

Pandas é uma biblioteca do Python usada para análise, manipulação e tratamento de dados.
Ela é muito utilizada em ciência de dados, machine learning, finanças, estatística e qualquer área que trabalhe com ***tabelas, planilhas ou bancos de dados.***<br>
Trabalha com DataFrame (tabelas) e Series (coluna única)

Ele permite:

*   Ler dados de planilhas (CSV, Excel, SQL, etc.)

*   Organizar dados em formato de tabela

*   Tratar valores nulos

*   Filtrar, selecionar, juntar e transformar dados

*   Fazer cálculos estatísticos (média, soma, contagem, etc.)

*   Criar novas colunas, agrupar e analisar conjuntos de dados




---



### **Instalação e importação de Pandas**

In [ ]:
# instalação do pandas
!pip install pandas #somente no colab precisa colocar o ! na instalação. No PyCharm ou VS Code a instalação é feita no terminal CMD e não precisa colocar o !.

In [3]:
import pandas as pd #importação e apelido dado para a biblioteca

In [ ]:
print (pd.__version__) #mostrar a versão instalada

2.2.2




---



### **Como criar um banco de dados do zero no código:**

In [ ]:
#Criação por: Series (como uma única coluna)
dados = pd.Series([10, 20, 30])
dados

0    10
1    20
2    30
dtype: int64

In [ ]:
#Criação por: DataFrames (como uma planilha)
dados = {
    "Nome": ["João", "Maria", "Pedro", "Ana"],
    "Idade": [25, 30, 35, 40],
    "Cidade": ["São Paulo", "Rio de Janeiro", "Belo Horizonte", "Porto Alegre"]
}
df = pd.DataFrame(dados)
print(df)

    Nome  Idade          Cidade
0   João     25       São Paulo
1  Maria     30  Rio de Janeiro
2  Pedro     35  Belo Horizonte
3    Ana     40    Porto Alegre




---



###  **Como ler um banco de dados externo**

In [ ]:
#precisa digitar esse código e colocar o arquivo que quer puxar aqui, já que o Colab roda na nuvem e não tem acesso direto aos arquivos do seu computador.
#no VSCode ou Pycharm não precisa rodar esse código
from google.colab import files
uploaded = files.upload()

Saving vendasprojeto.csv to vendasprojeto.csv


In [ ]:
#Por CVS: é um tipo de arquivo muito usado para guardar dados em forma de tabela, parecido com uma planilha do Excel.

df = pd.read_csv("vendasprojeto.csv")   #eu nomeei essa variável como df (de DataFrame), mas você pode colocar o nome que quiser (exemplo: tabela)
df

Data Produto   Categoria  Preco  Quantidade Vendedor
0  2024-01-01  Camisa      Roupas     50           3      Ana
1  2024-01-01   Calça      Roupas     80           2      Ana
2  2024-01-02   Tênis    Calçados    120           1    Pedro
3  2024-01-02   Meias    Calçados     10           5    Pedro
4  2024-01-03    Boné  Acessórios     30           2    Lucas
5  2024-01-03   Cinto  Acessórios     40           1    Lucas
6  2024-01-04  Camisa      Roupas     50           1      Ana
7  2024-01-04   Tênis    Calçados    120           2    Pedro
8  2024-01-05   Calça      Roupas     80           1      Ana
9  2024-01-05    Boné  Acessórios     30           3    Lucas

In [ ]:
from google.colab import files  #vou puxar outra base de dados agora, como xlsx (excel)
uploaded = files.upload()

Saving vendas_loja.xlsx to vendas_loja.xlsx


In [ ]:
#Por Excel:
df = pd.read_excel("vendas_loja.xlsx")
df

Data Produto   Categoria  Preco  Quantidade Vendedor
0  2024-01-01  Camisa      Roupas     50           3      Ana
1  2024-01-01   Calça      Roupas     80           2      Ana
2  2024-01-02   Tênis    Calçados    120           1    Pedro
3  2024-01-02   Meias    Calçados     10           5    Pedro
4  2024-01-03    Boné  Acessórios     30           2    Lucas
5  2024-01-03   Cinto  Acessórios     40           1    Lucas
6  2024-01-04  Camisa      Roupas     50           1      Ana
7  2024-01-04   Tênis    Calçados    120           2    Pedro
8  2024-01-05   Calça      Roupas     80           1      Ana
9  2024-01-05    Boné  Acessórios     30           3    Lucas

Agora, para puxar dados de um link do github:

In [4]:
#em formato csv
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/superstore_data.csv'  #se o arquivo estiver no github precisa gerar o link no raw
dados_mercado = pd.read_csv(url)
dados_mercado.head()

Id  Year_Birth   Education Marital_Status   Income  Kidhome  Teenhome  \
0   1826        1970  Graduation       Divorced  84835.0        0         0   
1      1        1961  Graduation         Single  57091.0        0         0   
2  10476        1958  Graduation        Married  67267.0        0         1   
3   1386        1967  Graduation       Together  32474.0        1         1   
4   5371        1989  Graduation         Single  21474.0        1         0   

  Dt_Customer  Recency  MntWines  ...  MntFishProducts  MntSweetProducts  \
0   6/16/2014        0       189  ...              111               189   
1   6/15/2014        0       464  ...                7                 0   
2   5/13/2014        0       134  ...               15                 2   
3   11/5/2014        0        10  ...                0                 0   
4    8/4/2014        0         6  ...               11                 0   

   MntGoldProds  NumDealsPurchases  NumWebPurchases  NumCatalogPurchases  \
0           218                  1                4                    4   
1            37                  1                7                    3   
2            30                  1                3                    2   
3             0                  1                1                    0   
4            34                  2                3                    1   

   NumStorePurchases  NumWebVisitsMonth  Response  Complain  
0                  6                  1         1         0  
1                  7                  5         1         0  
2                  5                  2         0         0  
3                  2                  7         0         0  
4                  2                  7         1         0  

[5 rows x 22 columns]

In [6]:
dados_mercado = pd.read_csv(url, nrows=3) #caso eu queira que me mostre só 3 linhas
dados_mercado.head()

Id  Year_Birth   Education Marital_Status  Income  Kidhome  Teenhome  \
0   1826        1970  Graduation       Divorced   84835        0         0   
1      1        1961  Graduation         Single   57091        0         0   
2  10476        1958  Graduation        Married   67267        0         1   

  Dt_Customer  Recency  MntWines  ...  MntFishProducts  MntSweetProducts  \
0   6/16/2014        0       189  ...              111               189   
1   6/15/2014        0       464  ...                7                 0   
2   5/13/2014        0       134  ...               15                 2   

   MntGoldProds  NumDealsPurchases  NumWebPurchases  NumCatalogPurchases  \
0           218                  1                4                    4   
1            37                  1                7                    3   
2            30                  1                3                    2   

   NumStorePurchases  NumWebVisitsMonth  Response  Complain  
0                  6                  1         1         0  
1                  7                  5         1         0  
2                  5                  2         0         0  

[3 rows x 22 columns]

In [9]:
dados_selecao = pd.read_csv(url, usecols=['Id','Year_Birth','Marital_Status']) #caso eu queira que me mostre só colunas específicas
dados_selecao

Id  Year_Birth Marital_Status
0      1826        1970       Divorced
1         1        1961         Single
2     10476        1958        Married
3      1386        1967       Together
4      5371        1989         Single
...     ...         ...            ...
2235  10142        1976       Divorced
2236   5263        1977        Married
2237     22        1976       Divorced
2238    528        1978        Married
2239   4070        1969        Married

[2240 rows x 3 columns]

Caso os dados do link não estejam separados por vírgula, mas por exemplo separados por ; (ponto e vírgula):<br>
exemplo <br>
nome;idade;cidade;profissao
Jovana;29;São Paulo;Analista de Dados
Carlos;32;Campinas;Administrador
Ana;25;Belo Horizonte;Estudante

In [5]:
url_2 = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/superstore_data_ponto_virgula.csv'
dados_ponto_virgula = pd.read_csv(url_2, sep = ';')  #sep = ';'
dados_ponto_virgula.head()

Id  Year_Birth   Education Marital_Status   Income  Kidhome  Teenhome  \
0   1826        1970  Graduation       Divorced  84835.0        0         0   
1      1        1961  Graduation         Single  57091.0        0         0   
2  10476        1958  Graduation        Married  67267.0        0         1   
3   1386        1967  Graduation       Together  32474.0        1         1   
4   5371        1989  Graduation         Single  21474.0        1         0   

  Dt_Customer  Recency  MntWines  ...  MntFishProducts  MntSweetProducts  \
0   6/16/2014        0       189  ...              111               189   
1   6/15/2014        0       464  ...                7                 0   
2   5/13/2014        0       134  ...               15                 2   
3   11/5/2014        0        10  ...                0                 0   
4    8/4/2014        0         6  ...               11                 0   

   MntGoldProds  NumDealsPurchases  NumWebPurchases  NumCatalogPurchases  \
0           218                  1                4                    4   
1            37                  1                7                    3   
2            30                  1                3                    2   
3             0                  1                1                    0   
4            34                  2                3                    1   

   NumStorePurchases  NumWebVisitsMonth  Response  Complain  
0                  6                  1         1         0  
1                  7                  5         1         0  
2                  5                  2         0         0  
3                  2                  7         0         0  
4                  2                  7         1         0  

[5 rows x 22 columns]

In [12]:
#em formato excel
url = 'https://github.com/alura-cursos/Pandas/blob/main/emissoes_CO2.xlsx?raw=True' #colocar ?raw=True após o link para carregar o arquivo bruto
dados_co2 = pd.read_excel(url)
dados_co2.head()

País ISO 3166-1 alpha-3   Ano  Total  Carvão  Oléo  Gás  Cimento  \
0  Afeganistão                AFG  1750    0.0     NaN   NaN  NaN      NaN   
1  Afeganistão                AFG  1751    0.0     NaN   NaN  NaN      NaN   
2  Afeganistão                AFG  1752    0.0     NaN   NaN  NaN      NaN   
3  Afeganistão                AFG  1753    0.0     NaN   NaN  NaN      NaN   
4  Afeganistão                AFG  1754    0.0     NaN   NaN  NaN      NaN   

   Queima  Outro  Per Capita  
0     NaN    NaN         NaN  
1     NaN    NaN         NaN  
2     NaN    NaN         NaN  
3     NaN    NaN         NaN  
4     NaN    NaN         NaN

In [13]:
pd.ExcelFile(url).sheet_names #ver quantas abas tem nessa planilha

['emissoes_C02', 'emissoes_percapita', 'fontes']

In [16]:
#se eu quiser que mostre só as colunas de A até D da planilha dentro da aba emissoes_C02 e com número de linhas igual a 10:
intervalo = pd.read_excel(url, sheet_name='emissoes_C02', usecols= 'A:D', nrows=10)
intervalo

País ISO 3166-1 alpha-3   Ano  Total
0  Afeganistão                AFG  1750      0
1  Afeganistão                AFG  1751      0
2  Afeganistão                AFG  1752      0
3  Afeganistão                AFG  1753      0
4  Afeganistão                AFG  1754      0
5  Afeganistão                AFG  1755      0
6  Afeganistão                AFG  1756      0
7  Afeganistão                AFG  1757      0
8  Afeganistão                AFG  1758      0
9  Afeganistão                AFG  1759      0

Agora, lendo um arquivo que está na pasta do drive:

In [ ]:
dados = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/vendasprojeto.csv') #colar o caminho da pasta aqui
dados

Agora, lendo um arquivo que está no Google Sheets:

In [26]:
#1º copie o link da planilha no google sheets
# o link copiado foi: https://docs.google.com/spreadsheets/d/1-uwAJil72Qyn4ef71Vbxe4NNCzhA306_/edit?usp=sharing&ouid=109955090128011201599&rtpof=true&sd=true

sheet_id = '1-uwAJil72Qyn4ef71Vbxe4NNCzhA306_' #copiar a região do link acima que fica entre o /d/ e /edit?
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'
dados_co2_sheets = pd.read_csv(url)
dados_co2_sheets.head()

Apliques em acrilico  R$ 23,00 Unnamed: 2
0              Cola + Contact  R$ 25,00        NaN
1    Pigmento preto e branco   R$ 23,00        NaN
2  glitter holográfico chunky  R$ 40,00        NaN
3    folha de ouro e de prata  R$ 28,00        NaN
4               vinil adesivo  R$ 15,00        NaN

Lendo um arquivo JSON:

In [ ]:
#faça o upload do arquivo json para o drive e copie o caminho dele
dados_pacientes = pd.read_json('/content/pacientes.json')
dados_pacientes

Lendo um arquivo de uma página HTML ou XML:

In [ ]:
#salve a página no seu computador como arquivo .html
#depois faça o upload do arquivo .html para o drive e copie o caminho dele

dados_html = pd.read_html('/content/filmes_wikipedia.html')
top_filmes = dados_html[1]
top_filmes

###  **Lendo tabelas que são muito grandes  - Visualização simplificada de dados**

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving tabela_duas_abas.xlsx to tabela_duas_abas (1).xlsx


In [ ]:
tabela = pd.read_excel("tabela_duas_abas.xlsx") #essa é a tabela normal, com todos os dados
tabela

ID     Produto  Quantidade  Preço        Data
0    1   Produto 1           2   10.5  2025-01-02
1    2   Produto 2           3   11.0  2025-01-03
2    3   Produto 3           4   11.5  2025-01-04
3    4   Produto 4           5   12.0  2025-01-05
4    5   Produto 5           1   12.5  2025-01-06
5    6   Produto 6           2   13.0  2025-01-07
6    7   Produto 7           3   13.5  2025-01-08
7    8   Produto 8           4   14.0  2025-01-09
8    9   Produto 9           5   14.5  2025-01-10
9   10  Produto 10           1   15.0  2025-01-11
10  11  Produto 11           2   15.5  2025-01-12
11  12  Produto 12           3   16.0  2025-01-13
12  13  Produto 13           4   16.5  2025-01-14
13  14  Produto 14           5   17.0  2025-01-15
14  15  Produto 15           1   17.5  2025-01-16
15  16  Produto 16           2   18.0  2025-01-17
16  17  Produto 17           3   18.5  2025-01-18
17  18  Produto 18           4   19.0  2025-01-19
18  19  Produto 19           5   19.5  2025-01-20
19  20  Produto 20           1   20.0  2025-01-21
20  21  Produto 21           2   20.5  2025-01-22
21  22  Produto 22           3   21.0  2025-01-23
22  23  Produto 23           4   21.5  2025-01-24
23  24  Produto 24           5   22.0  2025-01-25
24  25  Produto 25           1   22.5  2025-01-26
25  26  Produto 26           2   23.0  2025-01-27
26  27  Produto 27           3   23.5  2025-01-28
27  28  Produto 28           4   24.0  2025-01-01
28  29  Produto 29           5   24.5  2025-01-02
29  30  Produto 30           1   25.0  2025-01-03

In [ ]:
#para facilitar sua vida, você pode ler somente as 5 primeiras linhas como esse método:
tabela.head()

ID    Produto  Quantidade  Preço        Data
0   1  Produto 1           2   10.5  2025-01-02
1   2  Produto 2           3   11.0  2025-01-03
2   3  Produto 3           4   11.5  2025-01-04
3   4  Produto 4           5   12.0  2025-01-05
4   5  Produto 5           1   12.5  2025-01-06

In [ ]:
#e se quiser ler 10 linhas (ou outra quantidade - você coloca a quantidade que quer dentro dos parênteses):
tabela.head(10)

ID     Produto  Quantidade  Preço        Data
0   1   Produto 1           2   10.5  2025-01-02
1   2   Produto 2           3   11.0  2025-01-03
2   3   Produto 3           4   11.5  2025-01-04
3   4   Produto 4           5   12.0  2025-01-05
4   5   Produto 5           1   12.5  2025-01-06
5   6   Produto 6           2   13.0  2025-01-07
6   7   Produto 7           3   13.5  2025-01-08
7   8   Produto 8           4   14.0  2025-01-09
8   9   Produto 9           5   14.5  2025-01-10
9  10  Produto 10           1   15.0  2025-01-11

In [ ]:
#ou pode ler somente as 5 últimas linhas:
tabela.tail()

ID     Produto  Quantidade  Preço        Data
25  26  Produto 26           2   23.0  2025-01-27
26  27  Produto 27           3   23.5  2025-01-28
27  28  Produto 28           4   24.0  2025-01-01
28  29  Produto 29           5   24.5  2025-01-02
29  30  Produto 30           1   25.0  2025-01-03

In [ ]:
tabela.tail(7)

ID     Produto  Quantidade  Preço        Data
23  24  Produto 24           5   22.0  2025-01-25
24  25  Produto 25           1   22.5  2025-01-26
25  26  Produto 26           2   23.0  2025-01-27
26  27  Produto 27           3   23.5  2025-01-28
27  28  Produto 28           4   24.0  2025-01-01
28  29  Produto 29           5   24.5  2025-01-02
29  30  Produto 30           1   25.0  2025-01-03

In [ ]:
#ah, mas a minha planilha de excel tem duas abas ou mais, como puxar os dados de uma aba específica?
tabela = pd.read_excel("tabela_duas_abas.xlsx", sheet_name="Clientes")  #sheet_name= colocar o nome da Aba que quer puxar.
tabela

ID    Nome          Cidade  Idade  Gasto_Total
0    1   Pedro  Rio de Janeiro     21          205
1    2   Maria  Belo Horizonte     22          210
2    3  Carlos        Curitiba     23          215
3    4    João       Fortaleza     24          220
4    5     Ana       São Paulo     25          225
5    6   Pedro  Rio de Janeiro     26          230
6    7   Maria  Belo Horizonte     27          235
7    8  Carlos        Curitiba     28          240
8    9    João       Fortaleza     29          245
9   10     Ana       São Paulo     30          250
10  11   Pedro  Rio de Janeiro     31          255
11  12   Maria  Belo Horizonte     32          260
12  13  Carlos        Curitiba     33          265
13  14    João       Fortaleza     34          270
14  15     Ana       São Paulo     20          275
15  16   Pedro  Rio de Janeiro     21          280
16  17   Maria  Belo Horizonte     22          285
17  18  Carlos        Curitiba     23          290
18  19    João       Fortaleza     24          295
19  20     Ana       São Paulo     25          300
20  21   Pedro  Rio de Janeiro     26          305
21  22   Maria  Belo Horizonte     27          310
22  23  Carlos        Curitiba     28          315
23  24    João       Fortaleza     29          320
24  25     Ana       São Paulo     30          325
25  26   Pedro  Rio de Janeiro     31          330
26  27   Maria  Belo Horizonte     32          335
27  28  Carlos        Curitiba     33          340
28  29    João       Fortaleza     34          345
29  30     Ana       São Paulo     20          350

In [ ]:
#Se quiser ver só uma coluna específica:
tabela["Nome"]

0      Pedro
1      Maria
2     Carlos
3       João
4        Ana
5      Pedro
6      Maria
7     Carlos
8       João
9        Ana
10     Pedro
11     Maria
12    Carlos
13      João
14       Ana
15     Pedro
16     Maria
17    Carlos
18      João
19       Ana
20     Pedro
21     Maria
22    Carlos
23      João
24       Ana
25     Pedro
26     Maria
27    Carlos
28      João
29       Ana
Name: Nome, dtype: object

In [ ]:
#Se quiser ver só uma coluna e só das 10 primeiras linhas:
tabela["Nome"].head(10)

0     Pedro
1     Maria
2    Carlos
3      João
4       Ana
5     Pedro
6     Maria
7    Carlos
8      João
9       Ana
Name: Nome, dtype: object

In [ ]:
#Se quiser ver colunas específicas - sendo mais de 1 coluna:
tabela[["Nome", "Idade"]].head(4)

Nome  Idade
0   Pedro     21
1   Maria     22
2  Carlos     23
3    João     24

In [ ]:
# Selecionar linhas (filtros). Exemplo: selecionar pessoas com idade > 25:
tabela[tabela["Idade"] > 25].head(7)

ID    Nome          Cidade  Idade  Gasto_Total
5    6   Pedro  Rio de Janeiro     26          230
6    7   Maria  Belo Horizonte     27          235
7    8  Carlos        Curitiba     28          240
8    9    João       Fortaleza     29          245
9   10     Ana       São Paulo     30          250
10  11   Pedro  Rio de Janeiro     31          255
11  12   Maria  Belo Horizonte     32          260

In [ ]:
#Filtrar com várias condições:
tabela[(tabela["Idade"] > 20) & (tabela["Idade"] < 30)].head(8)

ID    Nome          Cidade  Idade  Gasto_Total
0   1   Pedro  Rio de Janeiro     21          205
1   2   Maria  Belo Horizonte     22          210
2   3  Carlos        Curitiba     23          215
3   4    João       Fortaleza     24          220
4   5     Ana       São Paulo     25          225
5   6   Pedro  Rio de Janeiro     26          230
6   7   Maria  Belo Horizonte     27          235
7   8  Carlos        Curitiba     28          240



---



### **Tratamento de dados nulos**

In [ ]:
from google.colab import files #colocando a tabela dentro do colab
uploaded = files.upload()

Saving projetodadosalterar.xlsx to projetodadosalterar.xlsx


In [ ]:
tabela = pd.read_excel("projetodadosalterar.xlsx") #mostrando a tabela completa
tabela

Data Produto   Categoria Preco  Quantidade Vendedor
0  2024-01-01  Camisa      Roupas    50           3      Ana
1         NaN   Calça      Roupas    80           2      Ana
2  2024-01-02   Tênis    Calçados   120           1    Pedro
3  2024-01-02     NaN    Calçados    10           5    Pedro
4  2024-01-03    Boné  Acessórios    30           2    Lucas
5  2024-01-03   Cinto         NaN    40           1      NaN
6  2024-01-04  Camisa      Roupas    50           1      Ana
7  2024-01-04   Tênis    Calçados   120           2    Pedro
8  2024-01-05   Calça      Roupas     -           1      Ana
9  2024-01-05    Boné  Acessórios    30           3    Lucas

Observe que na tabela acima apareceu dados como **NaN**.<br>
Isso significa que neste banco de dados, esses dados são nulos, ou seja, **estão em branco e não existem**. <br>
No Pandas, dados nulos aparecem como:
*   NaN (Not a Number)
*   None
*   célula vazia
*   valor ausente

In [ ]:
#supondo que a tabela seja enorme, mas você queira saber onde estão os dados nulos:
tabela.isnull().sum()

Data          1
Produto       1
Categoria     1
Preco         0
Quantidade    0
Vendedor      1
dtype: int64

In [ ]:
#ver linhas com nulos:
tabela[tabela.isnull().any(axis=1)]

Data Produto Categoria Preco  Quantidade Vendedor
1         NaN   Calça    Roupas    80           2      Ana
3  2024-01-02     NaN  Calçados    10           5    Pedro
5  2024-01-03   Cinto       NaN    40           1      NaN

In [ ]:
#remover dados nulos:
tabela.dropna()

Data Produto   Categoria Preco  Quantidade Vendedor
0  2024-01-01  Camisa      Roupas    50           3      Ana
2  2024-01-02   Tênis    Calçados   120           1    Pedro
4  2024-01-03    Boné  Acessórios    30           2    Lucas
6  2024-01-04  Camisa      Roupas    50           1      Ana
7  2024-01-04   Tênis    Calçados   120           2    Pedro
8  2024-01-05   Calça      Roupas     -           1      Ana
9  2024-01-05    Boné  Acessórios    30           3    Lucas

In [ ]:
tabela = pd.read_excel("projetodadosalterar.xlsx") #lendo a tabela completa sem alterações novamente, para que eu possa mostrar o próximo método.
tabela

Data Produto   Categoria Preco  Quantidade Vendedor
0  2024-01-01  Camisa      Roupas    50           3      Ana
1         NaN   Calça      Roupas    80           2      Ana
2  2024-01-02   Tênis    Calçados   120           1    Pedro
3  2024-01-02     NaN    Calçados    10           5    Pedro
4  2024-01-03    Boné  Acessórios    30           2    Lucas
5  2024-01-03   Cinto         NaN    40           1      NaN
6  2024-01-04  Camisa      Roupas    50           1      Ana
7  2024-01-04   Tênis    Calçados   120           2    Pedro
8  2024-01-05   Calça      Roupas     -           1      Ana
9  2024-01-05    Boné  Acessórios    30           3    Lucas

In [ ]:
#alterar dados nulos:
tabela.fillna(0) #Colocar dentro do parênteses o que você quer colocar no lugar do dado nulo.

Data Produto   Categoria Preco  Quantidade Vendedor
0  2024-01-01  Camisa      Roupas    50           3      Ana
1           0   Calça      Roupas    80           2      Ana
2  2024-01-02   Tênis    Calçados   120           1    Pedro
3  2024-01-02       0    Calçados    10           5    Pedro
4  2024-01-03    Boné  Acessórios    30           2    Lucas
5  2024-01-03   Cinto           0    40           1        0
6  2024-01-04  Camisa      Roupas    50           1      Ana
7  2024-01-04   Tênis    Calçados   120           2    Pedro
8  2024-01-05   Calça      Roupas     -           1      Ana
9  2024-01-05    Boné  Acessórios    30           3    Lucas

### **Manipulando colunas dentro da tabela**

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving colunas_pandas.csv to colunas_pandas.csv


In [ ]:
tabela = pd.read_csv("colunas_pandas.csv").head(5)
tabela

Nome  Idade Data_Registro  Salário Ativo  ID_Departamento  Salário_Anual
0  Beatriz     45    2024-01-01  5473.00   Sim              102       65676.00
1     João     37    2023-08-28  2890.25   Sim              104       34683.00
2    Lucas     43    2024-03-17  5844.52   Não              105       70134.24
3    Pedro     29    2022-03-10  4487.21   Sim              104       53846.52
4      Ana     39    2023-04-27  7221.10   Sim              103       86653.20

In [ ]:
#criando colunas dentro da tabela: Coloca o nome que quer dar para a coluna e atribui o valor que ela vai receber
#No exemplo abaixo coloquei "None", que significa "Nada" ou "Vazio"

tabela ["Coluna_nova"] = None
tabela

Nome  Idade Data_Registro  Salário Ativo  ID_Departamento  \
0  Beatriz     45    2024-01-01  5473.00   Sim              102   
1     João     37    2023-08-28  2890.25   Sim              104   
2    Lucas     43    2024-03-17  5844.52   Não              105   
3    Pedro     29    2022-03-10  4487.21   Sim              104   
4      Ana     39    2023-04-27  7221.10   Sim              103   

   Salário_Anual Coluna_nova  
0       65676.00        None  
1       34683.00        None  
2       70134.24        None  
3       53846.52        None  
4       86653.20        None

In [ ]:
tabela["Coluna_nova"] = "o que vc quiser colocar"
tabela

Nome  Idade Data_Registro  Salário Ativo  ID_Departamento  \
0  Beatriz     45    2024-01-01  5473.00   Sim              102   
1     João     37    2023-08-28  2890.25   Sim              104   
2    Lucas     43    2024-03-17  5844.52   Não              105   
3    Pedro     29    2022-03-10  4487.21   Sim              104   
4      Ana     39    2023-04-27  7221.10   Sim              103   

   Salário_Anual              Coluna_nova  
0       65676.00  o que vc quiser colocar  
1       34683.00  o que vc quiser colocar  
2       70134.24  o que vc quiser colocar  
3       53846.52  o que vc quiser colocar  
4       86653.20  o que vc quiser colocar

In [ ]:
#criando uma coluna e manipulando dados de uma coluna já existente para preencher a nova coluna:
#quero criar uma coluna de Salário Mensal na tabela

tabela ["Salário mensal"] = tabela ['Salário_Anual'] / 12
tabela

Nome  Idade Data_Registro  Salário Ativo  ID_Departamento  \
0  Beatriz     45    2024-01-01  5473.00   Sim              102   
1     João     37    2023-08-28  2890.25   Sim              104   
2    Lucas     43    2024-03-17  5844.52   Não              105   
3    Pedro     29    2022-03-10  4487.21   Sim              104   
4      Ana     39    2023-04-27  7221.10   Sim              103   

   Salário_Anual              Coluna_nova  Salário mensal  
0       65676.00  o que vc quiser colocar         5473.00  
1       34683.00  o que vc quiser colocar         2890.25  
2       70134.24  o que vc quiser colocar         5844.52  
3       53846.52  o que vc quiser colocar         4487.21  
4       86653.20  o que vc quiser colocar         7221.10

In [ ]:
#removendo uma coluna:
tabela = tabela.drop(columns=['Salário_Anual'])
tabela

Nome  Idade Data_Registro  Salário Ativo  ID_Departamento  \
0  Beatriz     45    2024-01-01  5473.00   Sim              102   
1     João     37    2023-08-28  2890.25   Sim              104   
2    Lucas     43    2024-03-17  5844.52   Não              105   
3    Pedro     29    2022-03-10  4487.21   Sim              104   
4      Ana     39    2023-04-27  7221.10   Sim              103   

               Coluna_nova  Salário mensal  
0  o que vc quiser colocar         5473.00  
1  o que vc quiser colocar         2890.25  
2  o que vc quiser colocar         5844.52  
3  o que vc quiser colocar         4487.21  
4  o que vc quiser colocar         7221.10

In [ ]:
tabela = tabela.drop(columns=["ID_Departamento", 'Coluna_nova']) #dá para apagar mais de uma coluna
tabela

Nome  Idade Data_Registro  Salário Ativo  Salário mensal
0  Beatriz     45    2024-01-01  5473.00   Sim         5473.00
1     João     37    2023-08-28  2890.25   Sim         2890.25
2    Lucas     43    2024-03-17  5844.52   Não         5844.52
3    Pedro     29    2022-03-10  4487.21   Sim         4487.21
4      Ana     39    2023-04-27  7221.10   Sim         7221.10

In [ ]:
#Reorganizar colunas

tabela = tabela[["Ativo", "Nome", "Idade", "Salário", "Data_Registro"]]   #Basta escrever na ordem que você quer
tabela

Ativo     Nome  Idade  Salário Data_Registro
0   Sim  Beatriz     45  5473.00    2024-01-01
1   Sim     João     37  2890.25    2023-08-28
2   Não    Lucas     43  5844.52    2024-03-17
3   Sim    Pedro     29  4487.21    2022-03-10
4   Sim      Ana     39  7221.10    2023-04-27

In [ ]:
#Antes de reorganizar, é útil visualizar as colunas (útil se a tabela for enorme)
#Como saber quais colunas existem?

print(tabela.columns)

Index(['Ativo', 'Nome', 'Idade', 'Salário', 'Data_Registro'], dtype='object')


In [ ]:
#Renomeando colunas:

#quero trocar a palavra "Nome" por "Funcionário":

tabela.rename(columns = {"Nome": "Funcionário"}, inplace=True)   #inplace=True → altera direto no DataFrame (se remover, vai precisar salvar de novo em uma variável)
tabela

Ativo Funcionário  Idade  Salário Data_Registro
0   Sim     Beatriz     45  5473.00    2024-01-01
1   Sim        João     37  2890.25    2023-08-28
2   Não       Lucas     43  5844.52    2024-03-17
3   Sim       Pedro     29  4487.21    2022-03-10
4   Sim         Ana     39  7221.10    2023-04-27

In [ ]:
#Renomear várias colunas ao mesmo tempo

tabela.rename(columns={
    "Registro": "Admissão",
    "ID_Departamento": "Departamento",
    "Ativo": "Status"}, inplace=True)
tabela

Status Funcionário  Idade  Salário    Admissão
0    Sim     Beatriz     45  5473.00  2024-01-01
1    Sim        João     37  2890.25  2023-08-28
2    Não       Lucas     43  5844.52  2024-03-17
3    Sim       Pedro     29  4487.21  2022-03-10
4    Sim         Ana     39  7221.10  2023-04-27

In [ ]:
#Renomear dados que estão dentro das colunas:
#quero trocar o "Sim" por Ativo, e o "Não" por Inativo.

tabela["Status"] = tabela["Status"].replace({"Sim": "Ativo", "Não": "Inativo"})
tabela

Status Funcionário  Idade  Salário    Admissão
0    Ativo     Beatriz     45  5473.00  2024-01-01
1    Ativo        João     37  2890.25  2023-08-28
2  Inativo       Lucas     43  5844.52  2024-03-17
3    Ativo       Pedro     29  4487.21  2022-03-10
4    Ativo         Ana     39  7221.10  2023-04-27

### **Resumo e análise de dados**

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Papelaria_Vendas.xlsx to Papelaria_Vendas.xlsx


In [ ]:
df = pd.read_excel("Papelaria_Vendas.xlsx")
df

Dia da compra     Item                          Produto comprado  \
0      2025-02-07  Caderno        Caderno Brilhante 30 folhas Pretas   
1      2025-02-10  Caderno                  Caderno 50 folhas Kraft    
2      2025-02-10  Caderno        Caderno Brilhante 30 folhas Pretas   
3      2025-02-17  Caderno        Caderno Brilhante 30 folhas Pretas   
4      2025-02-20  Caderno       Caderno Preto Liso 30 folhas Pretas   
..            ...      ...                                       ...   
168    2025-11-10  Caderno  Caderno Preto Brilhante 50 folhas Pretas   
169    2025-11-10  Adesivo            1 cartela de adesivo: Love Red   
170    2025-11-10  Adesivo              1 cartela de adesivo Cristão   
171    2025-11-10  Caderno  Caderno Preto Brilhante 50 folhas Pretas   
172    2025-11-11  Caderno             Caderno Preto 30 folhas Kraft   

                  Local da compra  Recebido  
0                  Rio de Janeiro       8.0  
1                       Guarulhos       8.0  
2                          Paraná       8.0  
3                    Minas Gerais       8.0  
4                    São Paulo SP      12.0  
..                            ...       ...  
168  Belo Horizonte, Minas Gerais      12.0  
169         São Carlos, São Paulo       5.0  
170    Rio Vermelho, Minas Gerais       2.0  
171           Saltinho, São Paulo      12.0  
172            Peruíbe, São Paulo       8.0  

[173 rows x 5 columns]

In [ ]:
df.info()

#Mostra informações técnicas da tabela:quantas linhas e colunas tem, nome das colunas...
#...quantos valores não nulos, tipo de cada coluna (int, float, object/string…), memória usada

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173 entries, 0 to 172
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype         
---  ------            --------------  -----         
 0   Dia da compra     173 non-null    datetime64[ns]
 1   Item              173 non-null    object        
 2   Produto comprado  173 non-null    object        
 3   Local da compra   173 non-null    object        
 4   Recebido          173 non-null    float64       
dtypes: datetime64[ns](1), float64(1), object(3)
memory usage: 6.9+ KB


In [ ]:
#Somar dados de uma coluna:
#No caso, quero somar os valores da coluna "Recebido"

df["Recebido"].sum()

np.float64(1388.5)

In [ ]:
#Media de dados de uma coluna:

df["Recebido"].mean()

np.float64(8.026011560693641)

In [ ]:
#Máximo de dados de uma coluna:

df['Recebido'].max()

24.0

In [ ]:
#Mínimo de dados de uma coluna:

df['Recebido'].min()

0.0

In [ ]:
#Contagem de dados de uma coluna:
#Quero contar quantos itens tem na coluna "Item"

df['Item'].count()

np.int64(173)

In [ ]:
print("Soma dos valores Recebidos:", df['Recebido'].sum())
print("Média dos valores Recebidos:", df['Recebido'].mean())
print("Máximo dos valores Recebidos:", df['Recebido'].max())
print("Mínimo dos valores Recebidos:", df['Recebido'].min())
print("Contagem de Itens na tabela:", df['Item'].count())

Soma dos valores Recebidos: 1388.5
Média dos valores Recebidos: 8.026011560693641
Máximo dos valores Recebidos: 24.0
Mínimo dos valores Recebidos: 0.0
Contagem de Itens na tabela: 173


In [ ]:
df['Recebido'].std()  #std = Desvio Padrão (Standard Deviation)

# É uma medida que mostra o quanto os valores estão espalhados em relação à média.
# Desvio padrão baixo → os valores estão próximos da média, pouca variação.
# Desvio padrão alto → os valores estão longe da média, muita variação.

4.715223334359555

In [ ]:
df['Recebido'].quantile([0.25, 0.50, 0.75])  #Quartis

#Imagine que você tem vários valores e coloca todos em ordem (do menor para o maior).
#Os quartis dividem essa lista em 4 partes iguais:
# |----25%----|----25%----|----25%----|----25%----|
#       Q1          Q2          Q3

# 25%:	1º quartil do código (Q1)	25% dos valores estão abaixo dele
# 50%:	2º quartil do código (Q2) = mediana	Metade dos valores estão abaixo
# 75%:	3º quartil do código (Q3)	75% dos valores estão abaixo

0.25     2.0
0.50    10.0
0.75    12.0
Name: Recebido, dtype: float64

Interpretando o resultado dos quartis acima:

*   Q1 (0.25): 2.0 - 25% das vendas receberam 2 reais ou menos
*   Q2 (0.50): 10.0 -  50% das vendas receberam 10 reais  ou menos (este é o valor mediano)
*    Q3 (0.75):  12.0 -  75% das vendas receberam R$ 12 reais  ou menos


In [ ]:
df.describe()   # O describe() já trás média, std, min, max, quartis…

#Traz um resumo estatístico das colunas numéricas: contagem (count), média (mean), desvio padrão (std), mínimo (min), Q1, Q2, Q3 (quartis), máximo (max)
#É super usado para entender a distribuição dos dados.

Dia da compra    Recebido
count                            173  173.000000
mean   2025-08-13 19:50:17.341040384    8.026012
min              2025-02-07 00:00:00    0.000000
25%              2025-06-29 00:00:00    2.000000
50%              2025-08-20 00:00:00   10.000000
75%              2025-10-21 00:00:00   12.000000
max              2025-11-11 00:00:00   24.000000
std                              NaN    4.715223

In [ ]:
#trocar um tipo de dado de uma coluna
#Exemplo: quero trocar o tipo de dado da coluna "Recebido" - Está como float e quero que seja número inteiro:

df["Recebido"] = df["Recebido"].astype(int)
df

Dia da compra     Item                          Produto comprado  \
0      2025-02-07  Caderno        Caderno Brilhante 30 folhas Pretas   
1      2025-02-10  Caderno                  Caderno 50 folhas Kraft    
2      2025-02-10  Caderno        Caderno Brilhante 30 folhas Pretas   
3      2025-02-17  Caderno        Caderno Brilhante 30 folhas Pretas   
4      2025-02-20  Caderno       Caderno Preto Liso 30 folhas Pretas   
..            ...      ...                                       ...   
168    2025-11-10  Caderno  Caderno Preto Brilhante 50 folhas Pretas   
169    2025-11-10  Adesivo            1 cartela de adesivo: Love Red   
170    2025-11-10  Adesivo              1 cartela de adesivo Cristão   
171    2025-11-10  Caderno  Caderno Preto Brilhante 50 folhas Pretas   
172    2025-11-11  Caderno             Caderno Preto 30 folhas Kraft   

                  Local da compra  Recebido  
0                  Rio de Janeiro         8  
1                       Guarulhos         8  
2                          Paraná         8  
3                    Minas Gerais         8  
4                    São Paulo SP        12  
..                            ...       ...  
168  Belo Horizonte, Minas Gerais        12  
169         São Carlos, São Paulo         5  
170    Rio Vermelho, Minas Gerais         2  
171           Saltinho, São Paulo        12  
172            Peruíbe, São Paulo         8  

[173 rows x 5 columns]

### **Contagem de Ocorrências**

In [ ]:
df = pd.read_excel("Papelaria_Vendas.xlsx")
df

Dia da compra     Item                          Produto comprado  \
0      2025-02-07  Caderno        Caderno Brilhante 30 folhas Pretas   
1      2025-02-10  Caderno                  Caderno 50 folhas Kraft    
2      2025-02-10  Caderno        Caderno Brilhante 30 folhas Pretas   
3      2025-02-17  Caderno        Caderno Brilhante 30 folhas Pretas   
4      2025-02-20  Caderno       Caderno Preto Liso 30 folhas Pretas   
..            ...      ...                                       ...   
168    2025-11-10  Caderno  Caderno Preto Brilhante 50 folhas Pretas   
169    2025-11-10  Adesivo            1 cartela de adesivo: Love Red   
170    2025-11-10  Adesivo              1 cartela de adesivo Cristão   
171    2025-11-10  Caderno  Caderno Preto Brilhante 50 folhas Pretas   
172    2025-11-11  Caderno             Caderno Preto 30 folhas Kraft   

                  Local da compra  Recebido  
0                  Rio de Janeiro       8.0  
1                       Guarulhos       8.0  
2                          Paraná       8.0  
3                    Minas Gerais       8.0  
4                    São Paulo SP      12.0  
..                            ...       ...  
168  Belo Horizonte, Minas Gerais      12.0  
169         São Carlos, São Paulo       5.0  
170    Rio Vermelho, Minas Gerais       2.0  
171           Saltinho, São Paulo      12.0  
172            Peruíbe, São Paulo       8.0  

[173 rows x 5 columns]

In [ ]:
df['Item'].value_counts()
#contagem de quantas vezes cada valor aparece em uma coluna
#Muito útil para descobrir: Item mais vendido, Cidade com mais compras, Quais valores são mais frequentes...

Item
Caderno              98
Adesivo              64
Caderno e Adesivo     2
Certificado           1
Name: count, dtype: int64

In [ ]:
df['Item'].value_counts().idxmax()

#idxmax(): Se aplicado em uma contagem, ele retorna o nome do item com o maior valor.

'Caderno'

In [ ]:
df['Item'].value_counts().idxmin()

#idxmin(): Se aplicado em uma contagem, ele retorna o nome do item com o menor valor.

'Certificado'

In [ ]:
print("Item mais vendido:", df['Item'].value_counts().idxmax())
print("Item menos vendido:", df['Item'].value_counts().idxmin())
print("Lugar que mais comprou:", df['Local da compra'].value_counts().idxmax())
print("Lugar que menos comprou:", df['Local da compra'].value_counts().idxmin())

Item mais vendido: Caderno
Item menos vendido: Certificado
Lugar que mais comprou: Não informado
Lugar que menos comprou: Paraná


Note que na resposta apareceu um "Não informado". Isso significa na coluna "Local da compra" tem campos com esse "Não informado".

In [ ]:
#identificar onde está o 'Não informado' na tabela:
df[df['Local da compra'] == 'Não informado']

Dia da compra     Item                            Produto comprado  \
76     2025-08-08  Caderno          Caderno Brilhante 30 folhas Pretas   
77     2025-08-08  Caderno          Caderno Brilhante 50 folhas Pretas   
139    2025-10-30  Caderno  Caderno Preto SEM glitter 50 folhas Pretas   
140    2025-10-30  Caderno  Caderno Preto SEM glitter 50 folhas Pretas   
141    2025-10-30  Caderno  Caderno Preto SEM glitter 50 folhas Pretas   
142    2025-10-30  Caderno  Caderno Preto SEM glitter 50 folhas Pretas   
143    2025-10-30  Caderno  Caderno Preto SEM glitter 50 folhas Pretas   
144    2025-10-30  Caderno  Caderno Preto SEM glitter 50 folhas Pretas   

    Local da compra  Recebido  
76    Não informado      10.0  
77    Não informado      12.0  
139   Não informado      12.0  
140   Não informado      12.0  
141   Não informado      12.0  
142   Não informado      12.0  
143   Não informado      12.0  
144   Não informado      12.0

In [ ]:
#Caso queira remover linhas com "Não informado":

df = df[df['Local da compra'] != 'Não informado']

In [ ]:
print("Lugar que mais comprou:", df['Local da compra'].value_counts().idxmax())

Lugar que mais comprou: Belo Horizonte, Minas Gerais


Caso queira fazer gráficos com esses dados, pode usar o Matplotlib.<br>
Assim com o Pandas, essa é outra Ferramenta de Python, mas o Matplotlib é para geração de **Gráficos.** <br>
Vou ensinar na próxima aula.

###**Operações de agregação**

**groupby()** É uma forma de agrupar dados por uma coluna e aplicar operações de agregação em outra(s).

In [ ]:
df = pd.read_excel("Papelaria_Vendas.xlsx")
df

Dia da compra     Item                          Produto comprado  \
0      2025-02-07  Caderno        Caderno Brilhante 30 folhas Pretas   
1      2025-02-10  Caderno                  Caderno 50 folhas Kraft    
2      2025-02-10  Caderno        Caderno Brilhante 30 folhas Pretas   
3      2025-02-17  Caderno        Caderno Brilhante 30 folhas Pretas   
4      2025-02-20  Caderno       Caderno Preto Liso 30 folhas Pretas   
..            ...      ...                                       ...   
168    2025-11-10  Caderno  Caderno Preto Brilhante 50 folhas Pretas   
169    2025-11-10  Adesivo            1 cartela de adesivo: Love Red   
170    2025-11-10  Adesivo              1 cartela de adesivo Cristão   
171    2025-11-10  Caderno  Caderno Preto Brilhante 50 folhas Pretas   
172    2025-11-11  Caderno             Caderno Preto 30 folhas Kraft   

                  Local da compra  Recebido  
0                  Rio de Janeiro       8.0  
1                       Guarulhos       8.0  
2                          Paraná       8.0  
3                    Minas Gerais       8.0  
4                    São Paulo SP      12.0  
..                            ...       ...  
168  Belo Horizonte, Minas Gerais      12.0  
169         São Carlos, São Paulo       5.0  
170    Rio Vermelho, Minas Gerais       2.0  
171           Saltinho, São Paulo      12.0  
172            Peruíbe, São Paulo       8.0  

[173 rows x 5 columns]

In [ ]:
#Quero ver o total de dinheiro recebido por cidade da tabela:

df.groupby('Local da compra')['Recebido'].sum()  #sum()=soma

Local da compra
 Belo Horizonte                              8.0
 Belo Horizonte, Minas Gerais                2.0
 Cachoeiro de Itapemirim, Espírito Santo     2.0
 Campinas, São Paulo                        12.0
 Campos dos Goytacazes, RJ                  12.0
                                            ... 
Vila Velha, Espírito Santo                  34.0
Vitória, Espírito Santo                      2.0
Volta Redonda, RJ                            8.0
Volta Redonda, Rio de Janeiro               12.0
Águas Formosas, Minas Gerais                12.0
Name: Recebido, Length: 136, dtype: float64

In [ ]:
df.groupby('Item')['Recebido'].mean() #Média recebida por item

Item
Adesivo               2.921875
Caderno              11.084906
Caderno e Adesivo    12.000000
Certificado           2.000000
Name: Recebido, dtype: float64

In [ ]:
df.groupby('Item')['Recebido'].mean().astype(int) #coloquei o resultado em números inteiros para visualizar melhor

Item
Adesivo               2
Caderno              11
Caderno e Adesivo    12
Certificado           2
Name: Recebido, dtype: int64

###**Ordenando valores**

**.sort_values()** é um método do Pandas para ordenar os valores

In [ ]:
#Quero ordenar os valores da coluna Recebido do maior para o menor

df.sort_values(by='Recebido', ascending=False).head(10)

#ascending=False: ordena do maior para o menor
# coloquei .head(10) no código para ver os 10 primeiros

Dia da compra               Item  \
57     2025-07-23            Caderno   
155    2025-11-04            Caderno   
15     2025-04-21            Caderno   
20     2025-04-27            Adesivo   
158    2025-11-06            Caderno   
156    2025-11-05            Caderno   
164    2025-11-08            Caderno   
79     2025-08-09  Caderno e Adesivo   
139    2025-10-30            Caderno   
141    2025-10-30            Caderno   

                                      Produto comprado  \
57       2 Cadernos Preto SEM glitter 50 folhas Pretas   
155      2 Cadernos Preto SEM glitter 50 folhas Pretas   
15                    2 Cadernos Preto 30 folhas Kraft   
20   1 cartela de adesivo: Love Red e Caderno Preto...   
158         Caderno Preto SEM glitter 50 folhas Pretas   
156         Caderno Preto SEM glitter 50 folhas Pretas   
164         Caderno Preto SEM glitter 50 folhas Pretas   
79   Caderno Preto SEM glitter 30 folhas Pretas\n1 ...   
139         Caderno Preto SEM glitter 50 folhas Pretas   
141         Caderno Preto SEM glitter 50 folhas Pretas   

                    Local da compra  Recebido  
57                      Diadema, SP        24  
155      Taboão da Serra, São Paulo        24  
15                   Nilópolis - RJ        16  
20                Curitiba - Paraná        16  
158  Rio de Janeiro, Rio de Janeiro        15  
156             Cruzeiro, São Paulo        15  
164    Belo Horizonte, Minas Gerais        15  
79     Belo Horizonte, Minas Gerais        14  
139                               -        12  
141                               -        12

In [ ]:
df.sort_values(by='Recebido', ascending=True).head(10)
#ascending=False: ordena do menor para o maior
# coloquei .head(10) no código para ver os 10 primeiros

Dia da compra     Item                    Produto comprado  \
14    2025-04-15  Adesivo  Adesivos Cristãos para Devocional    
13    2025-04-15  Adesivo      1 cartela de adesivo: Love Red   
11    2025-04-12  Adesivo      1 cartela de adesivo: Love Red   
12    2025-04-15  Adesivo      1 cartela de adesivo: Love Red   
26    2025-05-16  Adesivo                    Adesivo Love Red   
31    2025-05-22  Adesivo  Adesivos Cristãos para Devocional    
30    2025-05-20  Adesivo                    Adesivo Love Red   
28    2025-05-18  Adesivo  Adesivos Cristãos para Devocional    
44    2025-07-03  Adesivo      1 cartela de adesivo  Van Gogh   
38    2025-06-21  Adesivo                    Adesivo Love Red   

               Local da compra  Recebido  
14             Uberlândia - MG         0  
13                Birigui - SP         2  
11  Santa Rita do Sapucaí - MG         2  
12         Belo Horizonte - MG         2  
26         Ribeirão Preto - SP         2  
31            Carapicuíba - SP         2  
30           Salto - São Paulo         2  
28       São Paulo - São Paulo         2  
44     Lauro de Freitas, Bahia         2  
38             São Paulo\n, SP         2